### ISSUE TITLE
Add AQI for all pollutants

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/air-sampling#1]
Modify add_air_values so AQI is stored as data comes in

**Comment by KianBadie** [comment]
Did you happen to have an idea in mind of how the shape of the data would look with the new aqi values? Currently, we have:
`{ "aqi": 37.0, "time": 1669824693.0 "PM10": 22.17, ... }`

I'm guessing the new shape would look something like:

`{ "aqi": 37.0, "time": 1669824693.0 "PM10": {"aqi": 20, "concentration": 22.17}, ... }`

Or did you have something else in mind?

**Comment by tmorrell** [comment]
I was originally thinking just adding new variables like PM10_aqi, but your nested structure is cleaner. I'll go with your proposal unless you have other ideas.

**Comment by KianBadie** [comment]
Yeah, the two options I thought off were either the nested structure or variable naming like you mentioned. If it's convenient for you, then yes I would be happy to go with the nested structure!

**Comment by tmorrell** [comment]
I've implemented this, and it ended up being much easier to do them all as individual values. Hope it's not too much of a pain to modify.

```
{"PM2.5_aqi": 25.0, "NO": 1.05, "PM2.5": 6.0, "O3": 10.9, "PM10_aqi": 18.0, "CO_aqi": 0.0, "NO2_aqi": 31.0, "time": 1659392533.0, "CO": 1.0, "PM10": 19.6, "O3_aqi": 8.0, "NO2": 33.5, "temp": 21.1, "date": "2022-08-01", "SO2": 1.13, "pressure": 740.7, "NOy": 38.5, "aqi": 31.0}
```

At the moment these values will always be returned, until I get John to re-start the live data.

**Comment by KianBadie** [comment]
@tmorrell not a pain at all, I can work with this. Thank you!
