### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/air-sampling#10]
Add a footer with logos https://caltechsites-prod.s3.amazonaws.com/resnick/images/resnick_standard_msmall.max-250x250.jpg and https://data.caltech.edu/static/images/CaltechDATA-by-Caltech-Library-blue-with-padding.svg. Link to https://resnick.caltech.edu/ and https://data.caltech.edu/

**Comment by KianBadie** [comment]
@tmorrell hi Tom, I'd be happy to implement this. Do we just want the logos in a row across the bottom of the page? Seems simple enough that I could implement and we can change the size/spacing as needed after its merged.

**Comment by KianBadie** [comment]
@tmorrell I have added a very basic footer to the bottom of the test site. Please let me know if you'd like any changes!
