### ISSUE TITLE
Add primary pollutant

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/air-sampling#14]
Add primary pollutant to main AQI box. This is in the AQI_30_PRI value https://z44g6g2rrl.execute-api.us-west-2.amazonaws.com/test/get_air

For example when it's AQI_30_PRI: "PM2.5"

The main box should state "Primary Pollutant: PM₂₅" (Look either UTF8 or html subscript formatting, whichever looks better)

Once you install pandoc, you can render the site locally with `python _build.py`

You'll likely need to modify https://github.com/caltechlibrary/air-sampling/blob/18c2c8af354078076be09e9791800fbb87987269/scripts/index.js#L59

**Comment by RohanBhattaraiNP** [comment]
[](url
<img width="1509" alt="Screenshot 2024-10-04 at 10 36 29 PM" src="https://github.com/user-attachments/assets/5d7b75bd-9764-45f6-bb4f-4a6cf7aecfd4">

**Comment by RohanBhattaraiNP** [comment]
Waiting for merge.
