### ISSUE TITLE
Add temperature and overall AQI history

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/air-sampling#3]
Endpoint for last 24 hours

**Comment by KianBadie** [comment]
@tmorrell Did you happen to have an idea in mind for what the data from this endpoint will look like? If not, no worries. This is just for the case that I am able to start implementing the overall AQI chart so I can try to work with some dummy data. If it's still up in the air, I can make something up and just change it when the endpoint is live!

**Comment by tmorrell** [comment]
I think I’d implement it similar to the csv file we’re using for the other graphs. But very open to suggestions

On Dec 6, 2022, at 9:40 AM, Kian Badie ***@***.***> wrote:

﻿

@tmorrell<https://github.com/tmorrell> Did you happen to have an idea in mind for what the data from this endpoint will look like? If not, no worries. This is just for the case that I am able to start implementing the overall AQI chart so I can try to work with some dummy data. If it's still up in the air, I can make something up and just change it when the endpoint is live!

**Comment by KianBadie** [comment]
@tmorrell Got it, that makes sense. So this endpoint would be a csv with time, aqi, and temperature as the fields? That works with me!

**Comment by KianBadie** [comment]
@tmorrell Will the endpoint return the aqi/temp values for the past 24hrs starting from the current time? Ex: if it is 2pm on a Monday, will it return the values for 2pm Sunday - 2pm Monday. 

Or will it return the data for the current 24hr day? Ex: if it is 2pm on a Monday, it will return the data from 12am Monday - 2pm Monday.

John was able to provide a picture of what he had in mind for the chart [here](https://github.com/caltechlibrary/air-sampling/issues/8#issuecomment-1341663766) where it looks like the aqi chart will display the latter of what I mentioned. However, if the endpoint will return the former of what I mentioned and it is difficult to change that then I could likely filter the data client side. I don't think it would be too much of a problem to do that client side.

**Comment by tmorrell** [comment]
I'll do it by 24 hour day, that way you don't have to do any filtering. What do you want returned for the times that haven't elapsed yet? Is NA alright?

**Comment by KianBadie** [comment]
@tmorrell Awesome, thank you for doing that! If possible, I think it would be most convenient to do NaN, just because it would be consistent and predictable with how the current air data csv file treats undefined values.

**Comment by tmorrell** [comment]
Both temperature and aqi 24 hour traces are available at /get_air?graph=temp and /get_air?graph=aqi. Values that aren't defined arn't returned, since that reduces how much data we have to transfer and are more easily handled (data that isn't available doesn't go on the plot). I don't have the 7 day maximum and minimum implemented yet, since we need to make some other decisions about how we're doing the averaging first.

**Comment by KianBadie** [comment]
@tmorrell Awesome, so does this mean that each metric (curr_aqi, curr_temp, avg_aqi, avg_temp, avg_aqi_upper, etc...) will be it's own endpoint? And each endpoint will return a two column csv of timestamp/measurement values?

**Comment by tmorrell** [comment]
Yup!

On Dec 23, 2022, at 8:24 AM, Kian Badie ***@***.***> wrote:

﻿

@tmorrell<https://github.com/tmorrell> Awesome, so does this mean that each metric (curr_aqi, curr_temp, avg_aqi, avg_temp, avg_aqi_upper, etc...) will be it's own endpoint? And each endpoint will return a two column csv of timestamp/measurement values?

**Comment by KianBadie** [comment]
@tmorrell sounds good! Thanks for setting this up!

**Comment by KianBadie** [comment]
@tmorrell currently, it looks like the aqi/temp upper/lower values are not implemented yet. I was wondering if you had a timeframe in mind when that will be implemented. 

I hope that doesn't come off as rushing! I am just creating some dummy data right now and I wanted to see if I can make a timeframe for myself for when I would remove that dummy data and use the api instead.
