### ISSUE TITLE
Add graph endpoints

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/air-sampling#4]
With a selectable amount of time (days)

**Comment by tmorrell** [comment]
This is now available for a single day. We can start there and see if we need additional days of data. You can access any of the data in csv format by adding a graph query parameter to the get_air endpoint (e.g. `/get_air?graph=O3`). I'm using all the same labels as https://github.com/caltechlibrary/air-sampling/blob/main/air-values.json

Currently this is fixed to return just two test data points. I'll switch this off once live data returns. If you want to add more datapoints in the meantime, just push data with the date `2022-08-01` and time with the unix timestamp you for the time you want.

**Comment by KianBadie** [comment]
@tmorrell Is this the data that is going to be supplied to the pollutant charts? If so, does that mean that this data will replace [citaqs.txt](https://github.com/caltechlibrary/air-sampling/blob/main/citaqs.txt)?

If so, that is great. Working with individual endpoints will mean we no longer have to transform that csv data. So each pollutant endpoint will just return a two column csv file with timestamp/measurement values? 

Lastly, if this is replacing citaqs.txt, no worries on replicating the units row. I had to make another solution to supply units to the pollutant dropdown headers, so I can just use that same solution for this.

**Comment by tmorrell** [comment]
Yup, this will replace citaqs.txt. I figured out the query parameters, so this was actually easier to implement. I’m glad it makes things easier for you too!

On Dec 23, 2022, at 8:31 AM, Kian Badie ***@***.***> wrote:

﻿

@tmorrell<https://github.com/tmorrell> Is this the data that is going to be supplied to the pollutant charts? If so, does that mean that this data will replace citaqs.txt<https://github.com/caltechlibrary/air-sampling/blob/main/citaqs.txt>?

If so, that is great. Working with individual endpoints will mean we no longer have to transform that csv data. So each pollutant endpoint will just return a two column csv file with timestamp/measurement values?

Lastly, if this is replacing citaqs.txt, no worries on replicating the units row. I had to make another solution to supply units to the pollutant dropdown headers, so I can just use that same solution for this.

**Comment by KianBadie** [comment]
@tmorrell Nice, thanks Tom! Yes it indeed does.

I will go ahead and start replacing the data in the pollutant charts to be what is supplied through these endpoints.

**Comment by KianBadie** [comment]
@tmorrell I'm assuming the timestamp is in PST, correct?

**Comment by tmorrell** [comment]
Yeah, and I think we can always display the graphs in local time (no corrections or anything)

On Dec 23, 2022, at 11:12 AM, Kian Badie ***@***.***> wrote:

﻿

@tmorrell<https://github.com/tmorrell> I'm assuming the timestamp is in PST, correct?
