### ISSUE TITLE
Update displayed data in pollutant dropdown

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/air-sampling#5]
Display pollutant, concentration/unit, and aqi in top bar instead of pollutant, condition, concentration.

**Comment by KianBadie** [comment]
Here is a first draft of ideas to display the new pollutant information. I made 4 options: aqi style box, google style dot, and both options with a descriptor. The google style is a copy of what is displayed when you search "aqi" on google. Any thoughts or opinions? These can be tweaked in any way. I just wanted to get them out there to get the conversation started.

This is based off our meeting on yesterday. After making these I went back to mock sent in our recent email chain. The mentioned mock has the aqi labeled explicitly and units displayed differently. I think the explicit aqi label is good. Would you want the units displayed similarly?

Lastly, I'll mention the "use of color" accessibility concern I mentioned during our meeting. The guideline is meant to address those who can't perceive colors. That is why I added the descriptor options. Again, just wanted to put the option out there for you all in case that is something that was necessary. I know it was described as confusing if different pollutants had different descriptors, but if it adds anything to the discussion the www.airnow.gov/ site displays it in a similar way.

![pollutant-update](https://user-images.githubusercontent.com/18221058/204604956-e7682958-32e1-4aef-9eff-52eafd7abccf.png)
![mock](https://user-images.githubusercontent.com/18221058/204607198-9c447e01-13bc-4439-8df2-150cfff99abe.PNG)

**Comment by crounjd** [comment]
I like the green box around the AQI number.   I Like the bright green color!  This is what we want.
I think order from left to right is better as 'OZONE    AQI_number   Concentration_number'.  
I can take/or leave the category descriptor in the individual pollutants:  'Good', 'Moderate', ..., we just don't want to have contradictory advice, e.g. 'go outside' for ozone, at the same time as 'stay indoors' for PM!

Few other things:
-add units 'AQI'  with AQI number, otherwise this will be confusing
-add space between numbers and units
-format units: superscripts, 'mu' etc...
-Left justify (align) each column  
-units for CO:  Lets use 'ppbv'  rather than 'ppmv'

**Comment by KianBadie** [comment]
@crounjd got it. Bright colors is the direction to go in. I will use the colors denoted in the aqi documents. I will also swap the AQI and concentration order. Ah I see what you are saying. The current functionality is to only display "warnings" as described in the aqi [doc](https://www.airnow.gov/sites/default/files/2020-05/aqi-technical-assistance-document-sept2018.pdf), which seems to only define advisory statements for anything other than good. Can these warnings be mixed and matched? For example, the warning for moderate ozone being simultaneously displayed with the warning for unhealthy pm2.5?

As for your other notes, they are all noted and I will work on that!

**Comment by crounjd** [comment]
I think the warnings can be a little different for each pollutant.  So, we should probably keep them separate.

**Comment by KianBadie** [comment]
@crounjd My apologies, I think I made my question unclear. When I said mix and match and display simultaneously I meant that the warnings are still displayed in their respective pollutant dropdowns but at the same time. As in the moderate warning for ozone being displayed in it's own dropdown and if you scroll down to the pm2.5 dropdown it will also display it's own unhealthy warning but at a different level.

**Comment by crounjd** [comment]
@KianBadie Yes, I think each pollutant can have it's own particular warning, at the same time.

**Comment by KianBadie** [comment]
@crounjd sounds good!
