### ISSUE TITLE
Box shadows

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/air-sampling#7]
@crounjd One small thing I wanted to show you guys is what the site would look like with some box shadows. Personally, I feel they can make a site look nicer sometimes. So I wanted to show an example on this site in the case that you all felt the same. If this is something you are interested in, feel free to let me know! I added a before/after below.

# Before
![no-shadow](https://user-images.githubusercontent.com/18221058/205121357-d02b4c8f-8d52-4273-b5a4-56a065380fa6.PNG)
# After
![shadow](https://user-images.githubusercontent.com/18221058/205121349-f6de606c-daf8-4a97-82d6-2449f316ad88.PNG)

**Comment by crounjd** [comment]
I like the drop shadow.

**Comment by KianBadie** [comment]
@crounjd Sounds great! I will go ahead and add it in. If you would like me to tweak it or remove it please let me know!
