### ISSUE TITLE
Display overall AQI history

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/air-sampling#8]
Display chart of overall AQI history for last 24 hours.

**Comment by KianBadie** [comment]
@crounjd Below I have attached a general idea of what a top level AQI chart would look like using some fake data. The chart style is identical to the pollutant charts.

On mobile, I displayed the chart at a larger height so that the font size could be more readable. The tradeoff is that you have to horizontally scroll it, but I think it is worth it. If you would like to see the chart on mobile without scrolling required feel free to let me know.

What are your thoughts? Is this close to what you had in mind? When the data is live, the chart will display AQI data for the past 24 hours. Is that what was originally desired?

![desktop](https://user-images.githubusercontent.com/18221058/205991308-a314d4e9-3f05-4ed7-8fdc-ff9c77ab39d5.png)
![mobile](https://user-images.githubusercontent.com/18221058/205991325-1973ff31-2062-494c-8fa5-616e705bb2c6.png)

**Comment by crounjd** [comment]
@KianBadie I think the chart is good.  I wonder if it would look better to have the chart below the row containing AQI number, photo, news and links?  Regarding the time axis for the chart, I think this should start at 0 hrs local time and display thru 24 hrs local time, and current data will fill in across the chart as the day progresses, and time axis will not 'roll' with time.  In addition to displaying the AQI for the current day, it may be useful to display other traces, for instance 'Temperature', and perhaps the diurnal average AQI for the past week.  This may better give viewers an idea of what to expect for the future AQI.  I think scrolling on the mobile version is okay.  But it would be good to start the display with the current value in the center of the screen, then have scrolling left or right.

**Comment by KianBadie** [comment]
@crounjd I see what you are saying. I have attached some pictures of what the chart could look like underneath those elements. On mobile, I am assuming this should be under the AQI widget, unless you wanted it below the live cam element on mobile too. Let me know if that is something you would like to see.

I see, so for the time axis it will always display, let's say, 12am - 12am today. And the chart will be populated with whatever data fits in that time range currently. Is that correct?

Got it, so would temperature and possibly diurnal be on the same graph as the overall AQI graph?

Sounds good, I will see what I can do with starting the chart scrolled to the current value on mobile!

![desktop](https://user-images.githubusercontent.com/18221058/206278971-9139a703-49e7-4022-805a-67151ff0409a.gif)
![mobile](https://user-images.githubusercontent.com/18221058/206279653-32316122-46a3-41d9-b8c9-7666019a345d.png)

**Comment by crounjd** [comment]
@KianBadie I think both these look good.  Yes, I was thinking the chart x-axis would be 12AM current day to 12AM of next day.  Whatever data from current day available would be displayed (AQI, T).  Then, in addition, it may be useful to show previous data on the chart as well (maybe average from the past 7 days?).  The previous data could perhaps be displayed as light a light translucent color.  We don't want the chart to be confusing, but it would be useful to add context.  Perhaps previous data would look good showing the light color spanning +-1 standard deviation of data over the past 7 days, and maybe for both AQI and T?  I'm open to suggestions here, and we may need to iterate on this. Here is an example of what I was thinking:
<img width="822" alt="Screen Shot 2022-12-07 at 2 13 47 PM" src="https://user-images.githubusercontent.com/20955490/206308359-c936777d-5cbe-48a5-84b3-7a90037ad2f2.png">

**Comment by KianBadie** [comment]
@crounjd Got it, I'll stick with under the aqi, live cam, and links on desktop and only under the aqi widget on mobile. Thank you for the graphic as well, that makes this super clear!

I see, is the previous data something that was desired to be on the site if possible. Or is it something that is still up in the air if it is desired? From what I can see, I can say that if that previous data was displayed maybe it might be helpful to display somewhere what is being displayed. From your explanation, that chart is very clear in what is what. However, if I have never seen the chart before, I might have to guess what it is I am looking at with the lighter shade area graph behind the main line graphs.

In the meantime, I can fiddle around with the chart library we are using in how to implement a multiple line chart and possibly the area graph ideas.

**Comment by crounjd** [comment]
@KianBadie Great.  I think if the previous short-term average can be shown without too much work, it is something we want to do, as it adds substantial context.  I agree with your comment about the need to clearly label the data.  Perhaps this can be done simply enough with a legend on the chart, labeling all 4 traces? 
<img width="800" alt="Screen Shot 2022-12-08 at 9 34 51 AM" src="https://user-images.githubusercontent.com/20955490/206523539-17ed9ab6-21ce-4bf9-acac-edf8fb5d3ba8.png">

**Comment by crounjd** [comment]
@KianBadie Maybe better with horizontal legend?
<img width="848" alt="Screen Shot 2022-12-08 at 9 40 26 AM" src="https://user-images.githubusercontent.com/20955490/206524715-fb51ea66-7e43-40b3-a0f5-27e76f47dd0c.png">

**Comment by KianBadie** [comment]
@crounjd Got it! I'll add Tom to the discussion. From my current understanding, I think that would require making another api endpoint. And I think the legends look wonderful.

@tmorrell, do you think data for a 7 day average of aqi/temperature is something we can do? I am not sure yet if it is possible to show an area graph in the charts as mentioned in the comments above. But assuming it is, would that data require a new endpoint? What are your thoughts on that?

**Comment by tmorrell** [comment]
I think we can keep it at the same endpoint. So we'd have current_aqi, avg_aqi, dev_aqi, current_temp, avg_temp, dev_temp returned across the 24 hour day. The area would then be plotted from avg_aqi - dev_aqi to avg_aqi + dev_aqi. I could also return those upper and lower limits of the area if that would be easier.

**Comment by KianBadie** [comment]
@tmorrell great, thanks! So would dev_aqi and dev_temp be integers? And one would just +/- it from the avg values to plot the area graph?

And would the second option be to return the upper and lower limits per data point? As in an entry for a given time value 
 would be something like `timestamp: {avg_aqi, avg_aqi_upper, avg_aqi_lower}`? If so, that would be a little more convenient on my end, but if it is inconvenient on the api side then using the first option would still be easy to work with!

**Comment by tmorrell** [comment]
I'll do the second option `timestamp: {avg_aqi, avg_aqi_upper, avg_aqi_lower}`. It's easy to implement, and since this API is only for the dashboard we might as well make it match really closely to how we're doing the graphs

**Comment by KianBadie** [comment]
@tmorrell My apologies that I never replied to this, but thank you for doing it that way! Just to clarify, all of this will be on the endpoint described [here](https://github.com/caltechlibrary/air-sampling/issues/3), right? And that will be a csv file? If so, I'm assuming the columns would be: timestamp, curr_aqi, avg_aqi, avg_aqi_upper, and avg_aqi_lower (and the same for temperature). Would that assumption be correct?

**Comment by KianBadie** [comment]
@crounjd I've attached below a work in progress version of the aqi chart that I have been working on in my local branch. Minus actual data, some styling, and the legend, the graph resembles the one that you showed. In addition, it should be able to take in live data once it is up. Currently, temp and aqi have two values each (at midnight and 2pm).

All that said, I have a feeling the graph could use some tweaks but I am not sure yet. I wanted to show it to you to get some impressions. What are your thoughts on it so far? 

One thing I want to throw out there is to include patterns to the aqi/temp lines in addition to their color differentiation. Like dots along the aqi line and squares along the temp line. Something to that effect. That way, the chart could have a better chance of staying within accessibility guidelines that advise against relying solely on color.

![chart](https://user-images.githubusercontent.com/18221058/210704397-de92860c-4120-4756-b1cb-4f43596f3489.PNG)

**Comment by KianBadie** [comment]
@crounjd @tmorrell I think I got an initial version of the area graphs ready. As of right now, I am generating some fake data to generate the areas +/- 1.5 within that measurement's value. When the live data is up for the aqi and temp upper/lower values, I can swap those with the real data.

I can merge this onto the testing site if anyone would like it live to look at! If not, I will keep it in a separate branch for now and merge it when the aqi/temp upper/lower data is live.

![area](https://user-images.githubusercontent.com/18221058/211710563-7c7d7ade-77eb-4f3e-be67-ea97478fb1e3.PNG)

**Comment by crounjd** [comment]
@KianBadie I like it.  With regard to different symbols, I'm not sure we need this, given the spatial separation, but I'm open to discussion.  The colors (blue and red) were not chosen for any specific reason, so if someone has opinions for different colors, I am open to this.  

On the chart just above a couple comments:
-In my thinking, the purpose of showing the previous 7 day average is for predictive purposes, so it is important to show this for the complete 0-24 hr range, even when there is only data for the current day thru some fraction of the day.

@tmorrell I will work on trying to do the data averaging on my side.  For starters, I will work to generate 10-min and 1-hr averages.  Would you also like me to send the previous 7-day diurnal average data for AQI and temperature?  I do not currently calculate the AQI, so this may take a bit of work.

**Comment by KianBadie** [comment]
@crounjd That is good to hear! Ah I see, even though it was right in front of me I did not realize that the spatial separation is a way to differentiate the two. I guess, I was thinking in the scenario that both the temp/aqi are only a couple hours in, so both lines would be very close to the left side, which might initially look confusing. But I think for now I am also open to discussion on the topic and do not have any strong opinions toward one or the other. I also currently have no strong opinions on the color!

Got it, that makes sense! The graph can be set up to display whatever data is available. So if there is 24 hours worth of average data and a couple hours worth of the aqi/temp value data then the graph can display what is available. The average data shown in the graph above was to implement the feature with fake data in preparation for the live data (and the most convenient way to implement the fake data was to tweak the aqi/temp value data). But despite the difference in data, I hope the graph is still representative enough of the end goal to generate some feedback! However, if you think it would be helpful to see the 24 hour range of average data in the graph and in action, then feel free to let me know and I can generate some more fake data to display.

Also, I see that you are mentioning multiple types of averages. Does that mean that there will be multiple sets of area graphs for the aqi/temp? Or will it just be one line graph and one area graph for the aqi and temp each?

**Comment by KianBadie** [comment]
@crounjd I have merged some changes to the testing site. I have added the legend and functionality to display the upper/lower aqi/temp area graph. That data is not currently displayed, as the endpoint is not implemented yet. However, when the data is live, the area graph should show that data.

Please let me know if there are any changes you would like to see!
