### ISSUE TITLE
Formatting additions to pollutant charts

### ISSUE THREAD

**Issue by KianBadie** [caltechlibrary/air-sampling#9]
- [x] Replace "u" with mu character
- [x] Add super scripts to units
- [ ] Display time zone

**Comment by KianBadie** [comment]
@tmorrell Sorry for pinging you in so many messages this morning! I have another api related question. Currently, the air data csv file returns the units for each pollutant. I am assuming this csv file is generated with Python.  Would we be able to conveniently use utf 8 characters in that process? If so, we could use the Greek character "μ" as well as the superscript "³" in the unit names.

**Comment by KianBadie** [comment]
@crounjd One thing you mentioned in a previous meeting is the desire to show time zone in charts. When you said that, does that mean you wanted the charts to be displayed in PST to all users who are even outside of PST? Or does that mean that you wanted the time in the charts to be relativized to the time zone of the user?

I suppose the same question would also go for the time displayed in the top right corner of the site.

**Comment by KianBadie** [comment]
@crounjd I have just pushed some changes to the site to add time zone aware times in the aqi and pollutant charts as well as a x axis label to the pollutant charts describing it as Los Angeles local time. No matter the location, the time in the charts are intended to display the time in Los Angeles time (PST or PDT)

@tmorrell To do this, I relied on a third party [luxon](https://moment.github.io/luxon/#/). Working with timezones in JS turned out to be pretty tricky in my opinion, and luxon seemed to handle a lot of it. The difficulties arose when trying to create date objects that represented our timestamps in a way that reflected they were captured in Los Angeles time zone. However, if timestamps in the pollutant csv files were entered in UTC time I think that would remove the complications and reliance on the luxon library. I personally would prefer that, but I included the luxon library in case it was desired for the timestamp to stay the way it is. If there are any questions about this, I would be happy to explain more

**Comment by tmorrell** [comment]
I think we're good with the local time label. Only change I can see left is updating the ozone label from pppv to ppbv

**Comment by crounjd** [comment]
Also, I had a few other items on the graphs:
Can we use subscripts in the labels (2 places in graph axis label and overall label):

PM2.5 and PM10 --> PMsubscript(2.5) and PMsubscript(10)
NO2 and O3 --> NOsubscript(2) and Osubscript(3)

**Comment by crounjd** [comment]
Also, I wonder if there is room to add longer descriptor to each parameter, e.g.:
O3
Ozone

NO2
Nitrogen Dioxide

PM2.5
Particulate matter with diameter < 2.5 um

PM10
Particulate matter with diameter < 10 um

CO
Carbon Monoxide

**Comment by crounjd** [comment]
I also wonder if there is a way to highlight the primary pollutant?

**Comment by crounjd** [comment]
The primary pollutant could be listed in the AQI square at the top?  Unless you think there isn't room:

Primary Pollutant: Osubscript(3)

**Comment by crounjd** [comment]
Another formatting item:  add 'v' tp 'ppb' unit on NO2 plot (2 places), to match other units.  Also, it may be worthwhile to define units somewhere?  (1 ppbv == 1 part per billion parts of air;  1 ug / m^3 == 1 microgram per cubic meter of air )

**Comment by KianBadie** [comment]
> Also, I had a few other items on the graphs: Can we use subscripts in the labels (2 places in graph axis label and overall label):
> 
> PM2.5 and PM10 --> PMsubscript(2.5) and PMsubscript(10) NO2 and O3 --> NOsubscript(2) and Osubscript(3)

@crounjd I have now added the subscripts to the overall title. Good catch! However, I am not seeing what you are describing in the charts. The chart labels already have the subscripts you described. Please let me know if I am missing something. It is possible I have unknowingly fixed this after you commented this as well.

**Comment by crounjd** [comment]
> > Also, I had a few other items on the graphs: Can we use subscripts in the labels (2 places in graph axis label and overall label):
> > PM2.5 and PM10 --> PMsubscript(2.5) and PMsubscript(10) NO2 and O3 --> NOsubscript(2) and Osubscript(3)
> 
> @crounjd I have now added the subscripts to the overall title. Good catch! However, I am not seeing what you are describing in the charts. The chart labels already have the subscripts you described. Please let me know if I am missing something. It is possible I have unknowingly fixed this after you commented this as well.

@KianBadie Maybe its how it's showing up on my browser?  I've copied and pasted what I see, and made annotations on top -- see attached pdf.
[aqi_mods.pdf](https://github.com/caltechlibrary/air-sampling/files/13292820/aqi_mods.pdf)

**Comment by tmorrell** [comment]
@crounjd Do you still see the missing subscripts on your browser? What browser are you using?

**Comment by tmorrell** [comment]
@KianBadie I think the last thing I see to clean up is making sure all the charts have the same local time axis. I think we can remove some of the luxon code...but didn't want to make any big changes and break the site.

**Comment by crounjd** [comment]
> @crounjd Do you still see the missing subscripts on your browser? What browser are you using?

@tmorrell @KianBadie  In Chrome and Safari browsers the subscripts look fine.  In FireFox browser the subscripts in the chart axis labels don't seem to work (look same as picture I posted above), superscripts however seem to work, go figure!

**Comment by crounjd** [comment]
@KianBadie One other thought, for the individual parameter plots, can we show the graph time range from 0-24 hrs, and display the full band?  This will provide the viewer some context, and predictability.

**Comment by crounjd** [comment]
@KianBadie Also a couple subscripts could be made in the 'About PM' link under 'Useful Links' near the top right of the page.

**Comment by tmorrell** [comment]
@crounjd I took care of the 'Useful links' subscript updates.
